language: node_js
node_js:
  - 0.10
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - echo 'yes' | sudo add-apt-repository ppa:ubuntu-mozilla-daily/ppa
  - sudo apt-get update
  - sudo apt-get install firefox-trunk
  - export FIREFOX_NIGHTLY_BIN=$(which firefox-trunk)
  - npm run bower-install